include:
- ./func/*
kind: ArchiveUploadSpec
name: func-qKV1

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-w8-ben-fn-15bd0402-af65-45c7-91b3-37eda98eeaf0
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: update-w8-ben-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-qKV1
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-14T00:48:22Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-w8-ben-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: update-w8-ben-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_w8_ben
    packageref:
      name: update-w8-ben-fn-15bd0402-af65-45c7-91b3-37eda98eeaf0
      namespace: default
  requestsPerPod: 1
  resources: {}
