include:
- ./func/*
kind: ArchiveUploadSpec
name: func-Ann4

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: update-w8-ben-signature-fn-99e8c421-44c7-4d76-af92-8d180f53aa74
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: update-w8-ben-signature-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-Ann4
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-13T20:19:46Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: update-w8-ben-signature-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: update-w8-ben-signature-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.update_w8_ben_signature
    packageref:
      name: update-w8-ben-signature-fn-99e8c421-44c7-4d76-af92-8d180f53aa74
      namespace: default
  requestsPerPod: 1
  resources: {}
